title: Be My Rubber Duck by Titicat
logo: /assets/img/nuko.jpg
description: Blog about projects cooked up on the whim! Music/Coding contests/Games
github_username:  teacup123123

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
