title: Be My Rubber Duck by Titicat
logo: /assets/img/nuko.jpg
description: Music/Coding contests/Games. Random projects!
github_username:  teacup123123

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
