title: Titicat's coding blog
logo: /assets/img/logo.png
description: A blog about random projects cooked up on the whim! Music/Coding contests/Games
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

markdown: kramdown
permalink: /:year/:title:output_ext